name: Build
on:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    environment: build
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v3
      - name: Install node packages
        run: npm install
      - name: Build package
        run: npm run build
      - name: Run tests and publish coverage data to coveralls.io
        run: npm test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
